site_name: AIOsense

repo_name: Schluggi/AIOsense
repo_url: https://github.com/Schluggi/AIOsense

theme:
  name: material
  highlightjs: true
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - awesome-pages:
      filename: nav.yml
      strict: false
  - search
  - social
  - tags

markdown_extensions:
  - attr_list  # for image scale
