site_name: AIOsense

site_url: https://aiosense.readthedocs.io/en/latest/
repo_url: https://github.com/Schluggi/AIOsense
edit_uri: https://github.com/Schluggi/AIOsense/edit/main/docs

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
  - awesome-pages:
      filename: nav.yml
      strict: false
