substitutions:
  buzzer_pin: GPIO13
  i2s_bclk_pin: GPIO47 #SCK
  i2s_din_pin: GPIO46 #SD
  i2s_lrclk_pin: GPIO15 #WS
  pir_pin: GPIO11
  rgb_led_pin: GPIO48
  rgb_led_type: RGB
  sen0395_io_pin: GPIO4
  uart_rx_pin: GPIO43
  uart_tx_pin: GPIO44

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 32MB
  framework:
    type: esp-idf
    # version: 5.3.1 #https://github.com/espressif/esp-idf/releases
    # platform_version: 6.9.0 #https://github.com/platformio/platform-espressif32/releases/

i2c:
  sda: GPIO38
  scl: GPIO45
  frequency: 400kHz

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"

psram:
  mode: octal
  speed: 80MHz
