bme68x_bsec2_i2c:
  address: "0x77"
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  temperature_offset: "-6"

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    iaq:
      name: "IAQ"
      id: iaq
    co2_equivalent:
      name: "CO2 Equivalent"
    breath_voc_equivalent:
      name: "VOC Equivalent"
