globals:
  - id: display_state
    type: int
    restore_value: no
    initial_value: '0'

font:
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 18
  - file: "gfonts://Roboto"
    id: roboto_large
    size: 36

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      if (id(display_state) == 0) {
        it.printf(0, 0, id(roboto_small), "Temperature");
        it.printf(0, 20, id(roboto_large), "%.1f°F", (id(temperature).state * 1.8) + 32.0);
      } else if (id(display_state) == 1) {
        it.printf(0, 0, id(roboto_small), "Humidity");
        it.printf(0, 20, id(roboto_large), "%.1f%%", id(humidity).state);
      } else if (id(display_state) == 2) {
        it.printf(0, 0, id(roboto_small), "AQI");
        it.printf(0, 20, id(roboto_large), "%.1f", id(iaq).state);
      } else if (id(display_state) == 3) {
        it.printf(0, 0, id(roboto_small), "Time:");
        it.strftime(0, 20, id(roboto_large), "%I:%M %p", id(rtc_time).now());
      }


time:
  - platform: ds3231
    id: rtc_time

interval:
  - interval: 5s
    then:
      - lambda: |-
          id(display_state) += 1;
          if (id(display_state) > 3) {
            id(display_state) = 0;
          }
