external_components:
  - source: github://pr#5674
    components: [ ld2450 ]
    refresh: 0s

uart:
  id: uart_bus
  rx_pin: 
    number: "${uart_rx_pin}"
    mode:
      input: true
      pullup: true
  tx_pin: 
    number: "${uart_tx_pin}"
    mode:
      input: true
      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_bus
  throttle: 100ms

binary_sensor:
- platform: ld2450
  ld2450_id: ld2450_radar
  has_target:
    name: mmWave
    id: motion_mmwave
  has_moving_target:
    name: mmWave Moving Target
  has_still_target:
    name: mmWave Still Target

number:
- platform: ld2450
  ld2450_id: ld2450_radar
  presence_timeout:
    name: "mmWave Presence timeout"
  zone_1:
    x1:
      name: Zone1 X-Begin
      mode: box
    y1:
      name: Zone1 Y-Begin
      mode: box
    x2:
      name: Zone1 X-End
      mode: box
    y2:
      name: Zone1 Y-End
      mode: box
  zone_2:
    x1:
      name: Zone2 X-Begin
      mode: box
    y1:
      name: Zone2 Y-Begin
      mode: box
    x2:
      name: Zone2 X-End
      mode: box
    y2:
      name: Zone2 Y-End
      mode: box
  zone_3:
    x1:
      name: Zone3 X-Begin
      mode: box
    y1:
      name: Zone3 Y-Begin
      mode: box
    x2:
      name: Zone3 X-End
      mode: box
    y2:
      name: Zone3 Y-End
      mode: box

switch:
- platform: ld2450
  ld2450_id: ld2450_radar
  bluetooth:
    name: "mmWave Bluetooth"
  multi_target:
    name: "mmWave Multi Target"

select:
- platform: ld2450
  ld2450_id: ld2450_radar
  zone_type:
    name: "mmWave Zone Type"

button:
- platform: ld2450
  ld2450_id: ld2450_radar
  factory_reset:
    name: "mmWave Factory Reset"
    entity_category: "config"
  restart:
    name: "mmWave Restart"
    entity_category: "config"

text_sensor:
- platform: ld2450
  ld2450_id: ld2450_radar
  version:
    name: "mmWave Firmware Version"
  mac_address:
    name: "mmWave MAC Address"
  target_1:
    direction:
      name: "mmWave Target1 Direction"
  target_2:
    direction:
      name: "mmWave Target2 Direction"
  target_3:
    direction:
      name: "mmWave Target3 Direction"
