esphome:
  on_boot:
    priority: -10
    then:
      - switch.turn_on: mmwave_multi_target

external_components:
  - source: github://pr#5674
    components: [ ld2450 ]
    refresh: 600s

uart:
  id: uart_bus
  rx_pin: 
    number: "${uart_tx_pin}"
    mode:
      input: true
      pullup: true
  tx_pin: 
    number: "${uart_rx_pin}"
    mode:
      input: true
      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_bus
  throttle: 300ms

binary_sensor:
- platform: ld2450
  ld2450_id: ld2450_radar
  has_target:
    name: mmWave
    id: motion_mmwave
  has_moving_target:
    name: mmWave Moving Target
  has_still_target:
    name: mmWave Still Target

number:
- platform: ld2450
  ld2450_id: ld2450_radar
  presence_timeout:
    name: "mmWave Presence timeout"
  zone_1:
    x1:
      name: Zone 1 X-Begin
      mode: box
    y1:
      name: Zone 1 Y-Begin
      mode: box
    x2:
      name: Zone 1 X-End
      mode: box
    y2:
      name: Zone 1 Y-End
      mode: box
  zone_2:
    x1:
      name: Zone 2 X-Begin
      mode: box
    y1:
      name: Zone 2 Y-Begin
      mode: box
    x2:
      name: Zone 2 X-End
      mode: box
    y2:
      name: Zone 2 Y-End
      mode: box
  zone_3:
    x1:
      name: Zone 3 X-Begin
      mode: box
    y1:
      name: Zone 3 Y-Begin
      mode: box
    x2:
      name: Zone 3 X-End
      mode: box
    y2:
      name: Zone 3 Y-End
      mode: box

switch:
- platform: ld2450
  ld2450_id: ld2450_radar
  bluetooth:
    name: "mmWave Bluetooth"
  multi_target:
    name: "mmWave Multi Target"
    id: mmwave_multi_target

select:
- platform: ld2450
  ld2450_id: ld2450_radar
  zone_type:
    name: "mmWave Zone Type"

button:
- platform: ld2450
  ld2450_id: ld2450_radar
  factory_reset:
    name: "mmWave Factory Reset"
    entity_category: "config"
  restart:
    name: "mmWave Restart"
    entity_category: "config"

text_sensor:
- platform: ld2450
  ld2450_id: ld2450_radar
  version:
    name: "mmWave Firmware Version"
  mac_address:
    name: "mmWave MAC Address"

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
    still_target_count:
      name: Still Target Count
    moving_target_count:
      name: Moving Target Count
    target_1:
      x:
        name: Target 1 X
      y:
        name: Target 1 Y
      speed:
        name: Target 1 Speed
      distance:
        name: Target 1 Distance
    target_2:
      x:
        name: Target 2 X
      y:
        name: Target 2 Y
      speed:
        name: Target 2 Speed
      distance:
        name: Target 2 Distance
    target_3:
      x:
        name: Target 3 X
      y:
        name: Target 3 Y 
      speed:
        name: Target 3 Speed
      distance:
        name: Target 3 Distance
    zone_1:
      target_count:
        name: Zone 1 All Target Count
      still_target_count:
        name: Zone 1 Still Target Count
      moving_target_count:
        name: Zone 1 Moving Target Count
    zone_2:
      target_count:
        name: Zone 2 All Target Count
      still_target_count:
        name: Zone 2 Still Target Count
      moving_target_count:
        name: Zone 2 Moving Target Count
    zone_3:
      target_count:
        name: Zone 3 All Target Count
      still_target_count:
        name: Zone 3 Still Target Count
      moving_target_count:
        name: Zone 3 Moving Target Count
