binary_sensor:
  - platform: template
    name: "Occupancy"
    id: occupancy
    device_class: occupancy
    lambda: |-
      // PIR sensor triggers occupancy
      if (id(motion_pir).state) {
        return true;
      }
      
      // mmWave keeps occupancy true, but only if PIR has triggered first
      if (id(occupancy).state && id(motion_mmwave).state) {
        return true;
      }
      
      // Default to false if neither PIR nor mmWave conditions are met
      return false;
