binary_sensor:
  - platform: template
    name: "Occupancy"
    id: occupancy
    device_class: occupancy
    lambda: |-
      static bool occupancy_active = false;

      // If PIR detects motion, set occupancy to on
      if (id(motion_pir).state) {
        occupancy_active = true;
      }

      // If occupancy is already on, mmWave can keep it on
      if (occupancy_active && id(motion_mmwave).state) {
        return true;
      }

      // Turn off occupancy if neither sensor detects motion
      if (!id(motion_pir).state && !id(motion_mmwave).state) {
        occupancy_active = false;
      }

      return occupancy_active;
