# https://esphome.io/components/light/neopixelbus.html
substitutions:
  led_strobe_on: 50ms
  led_strobe_off: 100ms

light:
  - platform: esp32_rmt_led_strip
    name: "LED"
    id: led
    rgb_order: "${rgb_led_type}"
    chipset: ws2812
    num_leds: 1
    pin: "${rgb_led_pin}"
    rmt_channel: 0
    icon: "mdi:led-outline"

esphome:
  on_boot:
    - priority: 0
      then:
        - light.turn_on: led
        - delay: 2s
        - light.turn_off: led
